/**
 * AUTO-GENERATED by scripts/gen-food-icons.mjs from scripts/food-icons.data.json.
 * DO NOT EDIT BY HAND — edit the data file and re-run the generator.
 *
 * Distinct flat icon per dish (idli != dosa != vada != …), designed via the
 * design-food-icons workflow. Generic dish art, no trademarks involved.
 */

/** A single drawing primitive in a 0..24 viewBox. Fields used depend on `k`. */
export interface FoodShape {
  k: 'ellipse' | 'circle' | 'rect' | 'tri' | 'poly' | 'line';
  cx?: number;
  cy?: number;
  rx?: number;
  ry?: number;
  r?: number;
  x?: number;
  y?: number;
  w?: number;
  h?: number;
  round?: number;
  points?: number[][];
  x1?: number;
  y1?: number;
  x2?: number;
  y2?: number;
  /** Palette token (see FOOD_PALETTE) or "none". */
  fill?: string;
  /** Palette token or "none". */
  stroke?: string;
  sw?: number;
}

export interface FoodIconDef {
  label: string;
  shapes: FoodShape[];
}

export type FoodKey =
  | 'idli'
  | 'dosa'
  | 'vada'
  | 'poori'
  | 'upma'
  | 'pongal'
  | 'paratha'
  | 'parotta'
  | 'uttapam'
  | 'appam'
  | 'idiyappam'
  | 'sambar'
  | 'chutney'
  | 'samosa'
  | 'bajji'
  | 'poha';

/** Palette token -> hex. Unknown tokens fall back to brown at render time. */
export const FOOD_PALETTE: Record<string, string> = {
  plate: '#E8EDF1',
  plateline: '#BAC4CE',
  steam: '#B2BDC8',
  white: '#FCFBF7',
  cream: '#F2E6C4',
  golden: '#E8A33D',
  deepgold: '#C8791A',
  amber: '#F4CD7A',
  brown: '#97592A',
  darkbrown: '#5E3917',
  ghee: '#F4C543',
  coconut: '#F3F0E6',
  green: '#67B25C',
  darkgreen: '#3C7A37',
  mustard: '#C28A1B',
  peppercorn: '#2C2824',
  tomato: '#E0552C',
  red: '#D13A28',
  maroon: '#8B2A21',
  peanut: '#D8B886'
};

export const FOOD_ICONS: Record<FoodKey, FoodIconDef> = {
  idli: {
    label: 'Idli',
    shapes: [
      { k: 'ellipse', cx: 12, cy: 17, rx: 9.5, ry: 3.8, fill: 'plate', stroke: 'plateline', sw: 1 },
      { k: 'line', x1: 7.5, y1: 5.5, x2: 7, y2: 3, stroke: 'steam', sw: 1.4 },
      { k: 'line', x1: 12, y1: 4.5, x2: 12, y2: 2.2, stroke: 'steam', sw: 1.4 },
      { k: 'line', x1: 16.5, y1: 5.5, x2: 17, y2: 3, stroke: 'steam', sw: 1.4 },
      {
        k: 'ellipse',
        cx: 7.6,
        cy: 13.8,
        rx: 4,
        ry: 3.6,
        fill: 'white',
        stroke: 'plateline',
        sw: 1.2
      },
      {
        k: 'ellipse',
        cx: 16.4,
        cy: 13.8,
        rx: 4,
        ry: 3.6,
        fill: 'white',
        stroke: 'plateline',
        sw: 1.2
      },
      {
        k: 'ellipse',
        cx: 12,
        cy: 12.8,
        rx: 4.4,
        ry: 4,
        fill: 'white',
        stroke: 'plateline',
        sw: 1.2
      },
      { k: 'line', x1: 8.2, y1: 15.6, x2: 15.8, y2: 15.6, stroke: 'plateline', sw: 1 }
    ]
  },
  dosa: {
    label: 'Dosa',
    shapes: [
      { k: 'ellipse', cx: 12, cy: 16.5, rx: 9.5, ry: 4, fill: 'plate', stroke: 'plateline', sw: 1 },
      {
        k: 'ellipse',
        cx: 12,
        cy: 16.2,
        rx: 6.8,
        ry: 2.5,
        fill: 'none',
        stroke: 'plateline',
        sw: 0.7
      },
      {
        k: 'poly',
        points: [
          [4.5, 16.6],
          [6.2, 13.2],
          [18.5, 13.6],
          [20, 15.2],
          [18.8, 16.8],
          [5.4, 17.2]
        ],
        fill: 'deepgold',
        stroke: 'brown',
        sw: 1.2
      },
      {
        k: 'poly',
        points: [
          [4.5, 16.6],
          [6.2, 13.2],
          [7.8, 13.4],
          [6, 16.9]
        ],
        fill: 'amber',
        stroke: 'none'
      },
      { k: 'line', x1: 9.5, y1: 13.5, x2: 10.3, y2: 16.9, stroke: 'brown', sw: 0.7 },
      { k: 'line', x1: 13, y1: 13.6, x2: 13.8, y2: 17, stroke: 'brown', sw: 0.7 },
      { k: 'line', x1: 16.2, y1: 13.7, x2: 17, y2: 16.9, stroke: 'brown', sw: 0.7 },
      { k: 'circle', cx: 18.5, cy: 15, r: 1.4, fill: 'coconut', stroke: 'plateline', sw: 0.6 }
    ]
  },
  vada: {
    label: 'Medu Vada',
    shapes: [
      {
        k: 'ellipse',
        cx: 12,
        cy: 15.5,
        rx: 9.5,
        ry: 4.6,
        fill: 'plate',
        stroke: 'plateline',
        sw: 1
      },
      {
        k: 'ellipse',
        cx: 15.6,
        cy: 12.4,
        rx: 4.4,
        ry: 3.9,
        fill: 'deepgold',
        stroke: 'brown',
        sw: 1.3
      },
      { k: 'ellipse', cx: 15.6, cy: 12.5, rx: 1.7, ry: 1.5, fill: 'plate', stroke: 'brown', sw: 1 },
      {
        k: 'ellipse',
        cx: 9.4,
        cy: 14.4,
        rx: 5.4,
        ry: 4.7,
        fill: 'golden',
        stroke: 'brown',
        sw: 1.5
      },
      {
        k: 'ellipse',
        cx: 9.4,
        cy: 14.5,
        rx: 2.1,
        ry: 1.9,
        fill: 'plate',
        stroke: 'brown',
        sw: 1.2
      },
      { k: 'ellipse', cx: 8, cy: 11.6, rx: 2.4, ry: 0.9, fill: 'amber', stroke: 'none' }
    ]
  },
  poori: {
    label: 'Poori',
    shapes: [
      { k: 'ellipse', cx: 12, cy: 19, rx: 9, ry: 2.4, fill: 'plate', stroke: 'plateline', sw: 1 },
      {
        k: 'ellipse',
        cx: 12,
        cy: 12.8,
        rx: 7.6,
        ry: 6.6,
        fill: 'deepgold',
        stroke: 'brown',
        sw: 1.2
      },
      { k: 'ellipse', cx: 12, cy: 13.4, rx: 6.4, ry: 5.2, fill: 'golden', stroke: 'none' },
      { k: 'ellipse', cx: 9.3, cy: 9.8, rx: 2.4, ry: 1.5, fill: 'amber', stroke: 'none' },
      { k: 'ellipse', cx: 8.8, cy: 9.2, rx: 1, ry: 0.7, fill: 'cream', stroke: 'none' },
      { k: 'ellipse', cx: 15, cy: 15, rx: 1.6, ry: 1, fill: 'deepgold', stroke: 'none' },
      { k: 'line', x1: 6.5, y1: 13, x2: 17.5, y2: 12.4, stroke: 'deepgold', sw: 1 }
    ]
  },
  upma: {
    label: 'Upma',
    shapes: [
      { k: 'ellipse', cx: 12, cy: 17, rx: 9, ry: 3, fill: 'plate', stroke: 'plateline', sw: 1 },
      {
        k: 'poly',
        points: [
          [3.2, 16],
          [4.8, 19.6],
          [8, 21.3],
          [12, 21.8],
          [16, 21.3],
          [19.2, 19.6],
          [20.8, 16]
        ],
        fill: 'white',
        stroke: 'plateline',
        sw: 1
      },
      { k: 'ellipse', cx: 12, cy: 15.8, rx: 8, ry: 2.5, fill: 'cream', stroke: 'none' },
      { k: 'ellipse', cx: 12, cy: 13.6, rx: 7, ry: 4, fill: 'golden', stroke: 'deepgold', sw: 0.8 },
      { k: 'circle', cx: 8.6, cy: 13.4, r: 0.6, fill: 'darkbrown', stroke: 'none' },
      { k: 'circle', cx: 13.4, cy: 11.8, r: 0.6, fill: 'mustard', stroke: 'none' },
      { k: 'circle', cx: 11, cy: 15, r: 0.55, fill: 'darkbrown', stroke: 'none' },
      {
        k: 'ellipse',
        cx: 15,
        cy: 13.2,
        rx: 0.95,
        ry: 0.5,
        fill: 'green',
        stroke: 'darkgreen',
        sw: 0.5
      }
    ]
  },
  pongal: {
    label: 'Pongal',
    shapes: [
      { k: 'ellipse', cx: 12, cy: 20, rx: 7.5, ry: 1.6, fill: 'plateline', stroke: 'none' },
      {
        k: 'poly',
        points: [
          [4.5, 14.5],
          [19.5, 14.5],
          [17.8, 19.5],
          [6.2, 19.5]
        ],
        fill: 'white',
        stroke: 'plateline',
        sw: 1.2
      },
      { k: 'ellipse', cx: 12, cy: 11.5, rx: 8, ry: 4.5, fill: 'cream', stroke: 'none' },
      { k: 'ellipse', cx: 12, cy: 10, rx: 6.6, ry: 3.6, fill: 'ghee', stroke: 'none' },
      { k: 'ellipse', cx: 13.5, cy: 9, rx: 2.4, ry: 1.1, fill: 'deepgold', stroke: 'none' },
      { k: 'circle', cx: 8.6, cy: 11, r: 0.7, fill: 'peppercorn', stroke: 'none' },
      { k: 'circle', cx: 11.4, cy: 12.6, r: 0.7, fill: 'peppercorn', stroke: 'none' },
      { k: 'circle', cx: 15.2, cy: 11.4, r: 0.7, fill: 'peppercorn', stroke: 'none' }
    ]
  },
  paratha: {
    label: 'Paratha',
    shapes: [
      { k: 'circle', cx: 12, cy: 12, r: 9.6, fill: 'deepgold', stroke: 'brown', sw: 1 },
      { k: 'circle', cx: 12, cy: 12, r: 8.8, fill: 'golden', stroke: 'none' },
      { k: 'circle', cx: 11.4, cy: 11.6, r: 6.4, fill: 'none', stroke: 'deepgold', sw: 1.3 },
      { k: 'circle', cx: 10.7, cy: 11, r: 3.6, fill: 'none', stroke: 'deepgold', sw: 1.3 },
      { k: 'circle', cx: 10.2, cy: 10.6, r: 1.4, fill: 'none', stroke: 'brown', sw: 1.2 },
      { k: 'ellipse', cx: 15.4, cy: 9.4, rx: 1.4, ry: 1, fill: 'brown', stroke: 'none' },
      { k: 'ellipse', cx: 13.6, cy: 15.8, rx: 1.3, ry: 0.95, fill: 'darkbrown', stroke: 'none' },
      { k: 'circle', cx: 8.2, cy: 15, r: 0.9, fill: 'darkbrown', stroke: 'none' }
    ]
  },
  parotta: {
    label: 'Parotta',
    shapes: [
      { k: 'circle', cx: 12, cy: 12, r: 9.4, fill: 'deepgold', stroke: 'brown', sw: 1.2 },
      { k: 'circle', cx: 12, cy: 12, r: 7.3, fill: 'golden', stroke: 'amber', sw: 1.3 },
      { k: 'circle', cx: 12, cy: 12, r: 5.1, fill: 'deepgold', stroke: 'amber', sw: 1.3 },
      { k: 'circle', cx: 12, cy: 12, r: 3, fill: 'golden', stroke: 'amber', sw: 1.3 },
      { k: 'circle', cx: 12, cy: 12, r: 1.2, fill: 'amber', stroke: 'brown', sw: 1 },
      {
        k: 'poly',
        points: [
          [12, 2.8],
          [13.1, 2.9],
          [14.6, 7.2],
          [12, 5.1],
          [9.4, 7.2],
          [10.9, 2.9]
        ],
        fill: 'none',
        stroke: 'darkbrown',
        sw: 1
      },
      { k: 'line', x1: 12, y1: 5.1, x2: 12, y2: 10.6, stroke: 'darkbrown', sw: 0.9 }
    ]
  },
  uttapam: {
    label: 'Uttapam',
    shapes: [
      { k: 'ellipse', cx: 12, cy: 17.4, rx: 9.2, ry: 3, fill: 'plate', stroke: 'plateline', sw: 1 },
      {
        k: 'ellipse',
        cx: 12,
        cy: 15.2,
        rx: 8,
        ry: 3.5,
        fill: 'deepgold',
        stroke: 'brown',
        sw: 1.2
      },
      { k: 'rect', x: 4, y: 12.4, w: 16, h: 3.4, fill: 'deepgold', stroke: 'none' },
      { k: 'ellipse', cx: 12, cy: 12.4, rx: 8, ry: 3.6, fill: 'golden', stroke: 'brown', sw: 1.2 },
      { k: 'circle', cx: 8.2, cy: 12, r: 1.05, fill: 'tomato', stroke: 'none' },
      { k: 'circle', cx: 13.4, cy: 10.9, r: 1, fill: 'green', stroke: 'none' },
      { k: 'circle', cx: 15.6, cy: 13, r: 1, fill: 'red', stroke: 'none' },
      { k: 'circle', cx: 10.6, cy: 13.4, r: 0.95, fill: 'white', stroke: 'plateline', sw: 0.6 }
    ]
  },
  appam: {
    label: 'Appam',
    shapes: [
      {
        k: 'ellipse',
        cx: 12,
        cy: 15.5,
        rx: 10,
        ry: 4.2,
        fill: 'plate',
        stroke: 'plateline',
        sw: 1
      },
      { k: 'ellipse', cx: 12, cy: 14, rx: 9.5, ry: 4.6, fill: 'white', stroke: 'cream', sw: 1.2 },
      { k: 'ellipse', cx: 12, cy: 13.6, rx: 7.2, ry: 3.2, fill: 'cream', stroke: 'none' },
      { k: 'ellipse', cx: 12, cy: 12.2, rx: 4.6, ry: 3.4, fill: 'white', stroke: 'cream', sw: 1 },
      { k: 'ellipse', cx: 12, cy: 11.3, rx: 3, ry: 2.4, fill: 'white', stroke: 'none' },
      { k: 'ellipse', cx: 11, cy: 10.4, rx: 1, ry: 0.7, fill: 'cream', stroke: 'none' }
    ]
  },
  idiyappam: {
    label: 'Idiyappam',
    shapes: [
      { k: 'ellipse', cx: 12, cy: 15, rx: 9.2, ry: 4.4, fill: 'plate', stroke: 'plateline', sw: 1 },
      {
        k: 'ellipse',
        cx: 12,
        cy: 12.6,
        rx: 7.2,
        ry: 4.8,
        fill: 'white',
        stroke: 'coconut',
        sw: 1.2
      },
      {
        k: 'ellipse',
        cx: 11.3,
        cy: 12.4,
        rx: 5.6,
        ry: 3.6,
        fill: 'none',
        stroke: 'coconut',
        sw: 0.9
      },
      {
        k: 'ellipse',
        cx: 12.8,
        cy: 12.9,
        rx: 5.2,
        ry: 3.2,
        fill: 'none',
        stroke: 'coconut',
        sw: 0.9
      },
      {
        k: 'ellipse',
        cx: 11.6,
        cy: 12.5,
        rx: 3.6,
        ry: 2.3,
        fill: 'none',
        stroke: 'coconut',
        sw: 0.9
      },
      {
        k: 'ellipse',
        cx: 12.6,
        cy: 12.8,
        rx: 3.3,
        ry: 2,
        fill: 'none',
        stroke: 'coconut',
        sw: 0.9
      },
      {
        k: 'ellipse',
        cx: 12.1,
        cy: 12.6,
        rx: 1.7,
        ry: 1.1,
        fill: 'none',
        stroke: 'coconut',
        sw: 0.9
      }
    ]
  },
  sambar: {
    label: 'Sambar',
    shapes: [
      { k: 'ellipse', cx: 12, cy: 21, rx: 8.5, ry: 1.5, fill: 'plateline', stroke: 'none' },
      {
        k: 'poly',
        points: [
          [3.5, 12],
          [20.5, 12],
          [18, 20],
          [6, 20]
        ],
        fill: 'white',
        stroke: 'darkbrown',
        sw: 1.2
      },
      { k: 'ellipse', cx: 12, cy: 12, rx: 8.5, ry: 2.6, fill: 'tomato', stroke: 'maroon', sw: 1.2 },
      {
        k: 'rect',
        x: 12,
        y: 11.2,
        w: 5.5,
        h: 1.5,
        round: 0.75,
        fill: 'darkgreen',
        stroke: 'maroon',
        sw: 0.6
      },
      { k: 'circle', cx: 8, cy: 12, r: 1.3, fill: 'red', stroke: 'maroon', sw: 0.5 },
      {
        k: 'poly',
        points: [
          [6.5, 11.6],
          [7.6, 10.2],
          [8.7, 11.6],
          [7.6, 12.4]
        ],
        fill: 'green',
        stroke: 'darkgreen',
        sw: 0.7
      },
      { k: 'line', x1: 10, y1: 9.3, x2: 11, y2: 6, stroke: 'steam', sw: 1.4 },
      { k: 'line', x1: 14, y1: 9.3, x2: 15, y2: 6, stroke: 'steam', sw: 1.4 }
    ]
  },
  chutney: {
    label: 'Coconut Chutney',
    shapes: [
      { k: 'ellipse', cx: 12, cy: 19, rx: 6.2, ry: 1.4, fill: 'plateline', stroke: 'none' },
      {
        k: 'poly',
        fill: 'plate',
        stroke: 'plateline',
        sw: 1,
        points: [
          [6.5, 14],
          [17.5, 14],
          [16, 19],
          [8, 19]
        ]
      },
      { k: 'ellipse', cx: 12, cy: 11.8, rx: 5.6, ry: 4.2, fill: 'coconut', stroke: 'none' },
      { k: 'ellipse', cx: 12, cy: 14, rx: 5.8, ry: 1.5, fill: 'white', stroke: 'plateline', sw: 1 },
      { k: 'circle', cx: 13.3, cy: 10.4, r: 1, fill: 'red', stroke: 'none' },
      { k: 'circle', cx: 10.6, cy: 11.3, r: 0.85, fill: 'darkgreen', stroke: 'none' }
    ]
  },
  samosa: {
    label: 'Samosa',
    shapes: [
      { k: 'ellipse', cx: 12, cy: 20, rx: 8.5, ry: 2, fill: 'plate', stroke: 'plateline', sw: 1 },
      {
        k: 'poly',
        points: [
          [11, 5],
          [20.5, 18.5],
          [3.5, 18.5]
        ],
        fill: 'golden',
        stroke: 'brown',
        sw: 1.5
      },
      {
        k: 'poly',
        points: [
          [11, 6.6],
          [17.6, 18],
          [6.4, 18]
        ],
        fill: 'deepgold',
        stroke: 'none'
      },
      { k: 'line', x1: 11, y1: 5, x2: 3.5, y2: 18.5, stroke: 'brown', sw: 1.3 },
      { k: 'line', x1: 9.7, y1: 7.4, x2: 5.2, y2: 15.2, stroke: 'deepgold', sw: 0.8 },
      { k: 'line', x1: 4.5, y1: 18.5, x2: 19.5, y2: 18.5, stroke: 'brown', sw: 1.4 }
    ]
  },
  bajji: {
    label: 'Bajji / Pakora',
    shapes: [
      { k: 'ellipse', cx: 12, cy: 18.4, rx: 9, ry: 2.4, fill: 'plate', stroke: 'plateline', sw: 1 },
      { k: 'circle', cx: 7.2, cy: 15.2, r: 3.7, fill: 'amber', stroke: 'darkbrown', sw: 1 },
      { k: 'circle', cx: 16.8, cy: 15, r: 3.6, fill: 'deepgold', stroke: 'darkbrown', sw: 1 },
      { k: 'circle', cx: 12, cy: 15.8, r: 4, fill: 'golden', stroke: 'brown', sw: 1 },
      { k: 'circle', cx: 9.2, cy: 11, r: 3.5, fill: 'deepgold', stroke: 'darkbrown', sw: 1 },
      { k: 'circle', cx: 14.6, cy: 10.6, r: 3.4, fill: 'amber', stroke: 'brown', sw: 1 },
      { k: 'circle', cx: 11.7, cy: 8, r: 2.9, fill: 'golden', stroke: 'darkbrown', sw: 1 },
      { k: 'circle', cx: 13.4, cy: 7.2, r: 1.5, fill: 'deepgold', stroke: 'brown', sw: 1 },
      { k: 'circle', cx: 9.6, cy: 13, r: 0.9, fill: 'ghee', stroke: 'none', sw: 0 }
    ]
  },
  poha: {
    label: 'Poha',
    shapes: [
      {
        k: 'ellipse',
        cx: 12,
        cy: 17.5,
        rx: 9.5,
        ry: 3.7,
        fill: 'plate',
        stroke: 'plateline',
        sw: 1
      },
      { k: 'ellipse', cx: 12, cy: 15.2, rx: 7.4, ry: 4, fill: 'cream', stroke: 'golden', sw: 1 },
      { k: 'ellipse', cx: 11.6, cy: 13.6, rx: 4.6, ry: 2.6, fill: 'golden', stroke: 'none' },
      { k: 'circle', cx: 8.6, cy: 15.4, r: 1.05, fill: 'peanut', stroke: 'brown', sw: 0.6 },
      { k: 'circle', cx: 13.8, cy: 16, r: 1.05, fill: 'peanut', stroke: 'brown', sw: 0.6 },
      { k: 'circle', cx: 11, cy: 16.6, r: 1, fill: 'peanut', stroke: 'brown', sw: 0.6 },
      {
        k: 'ellipse',
        cx: 12.6,
        cy: 13,
        rx: 1.2,
        ry: 0.7,
        fill: 'green',
        stroke: 'darkgreen',
        sw: 0.6
      },
      {
        k: 'tri',
        points: [
          [17.6, 12.8],
          [20.8, 14],
          [18.2, 15.8]
        ],
        fill: 'amber',
        stroke: 'deepgold',
        sw: 0.8
      }
    ]
  }
};

/** [keyword, foodKey] pairs, longest keyword first (most specific wins). */
export const FOOD_KEYWORDS: ReadonlyArray<readonly [string, FoodKey]> = [
  ['coconut chutney', 'chutney'],
  ['thengai chutney', 'chutney'],
  ['nariyal chutney', 'chutney'],
  ['flattened rice', 'poha'],
  ['string hopper', 'idiyappam'],
  ['white chutney', 'chutney'],
  ['puffed bread', 'poori'],
  ['khara pongal', 'pongal'],
  ['masala dosa', 'dosa'],
  ['fried bread', 'poori'],
  ['rice lentil', 'pongal'],
  ['paper dosa', 'dosa'],
  ['ven pongal', 'pongal'],
  ['idiyappam', 'idiyappam'],
  ['parantha', 'paratha'],
  ['parottha', 'paratha'],
  ['uthappam', 'uttapam'],
  ['palappam', 'appam'],
  ['idiappam', 'idiyappam'],
  ['punugulu', 'bajji'],
  ['paratha', 'paratha'],
  ['paranta', 'paratha'],
  ['parotta', 'parotta'],
  ['porotta', 'parotta'],
  ['barotta', 'parotta'],
  ['uttapam', 'uttapam'],
  ['ootapam', 'uttapam'],
  ['sambhar', 'sambar'],
  ['chutney', 'chutney'],
  ['samoosa', 'samosa'],
  ['pongal', 'pongal'],
  ['aappam', 'appam'],
  ['appams', 'appam'],
  ['semiya', 'idiyappam'],
  ['sambar', 'sambar'],
  ['samosa', 'samosa'],
  ['pakora', 'bajji'],
  ['pakoda', 'bajji'],
  ['idlis', 'idli'],
  ['idili', 'idli'],
  ['dosai', 'dosa'],
  ['vadai', 'vada'],
  ['poori', 'poori'],
  ['uppma', 'upma'],
  ['appam', 'appam'],
  ['aapam', 'appam'],
  ['sevai', 'idiyappam'],
  ['bajji', 'bajji'],
  ['bonda', 'bajji'],
  ['bhaji', 'bajji'],
  ['idli', 'idli'],
  ['idly', 'idli'],
  ['dosa', 'dosa'],
  ['vada', 'vada'],
  ['medu', 'vada'],
  ['puri', 'poori'],
  ['upma', 'upma'],
  ['baji', 'bajji'],
  ['poha', 'poha'],
  ['pova', 'poha'],
  ['aval', 'poha']
];
